### ISSUE TITLE
BioC2020 workshop requirements

### ISSUE THREAD

**Issue by lwaldron** [haibol2016/ATACseqQCWorkshop#2]
Are you still planning to present this at BioC2020? If so, please follow the template provided at https://bioc2020.bioconductor.org and make sure it passes checks by July 16, otherwise it will have to be removed from the program.

**Comment by lwaldron** [comment]
Also, note you can reach out for extra help on the #biocworkshopbook Slack channel on bioc-community. We can probably find extra 1-on-1 help for you too if you need it.

**Comment by seaYali** [comment]
Hello Levi,

    Thanks for the reminder. I will work on it today and tomorrow.

Best,

Haibo

**Comment by seaYali** [comment]
Hello Levi,

    I have updated my workshop materials in my GitHub repository:
haibol2016/ATACseqQCWorkshop. However,  I am not familiar with the docker
container. Should do anything to build a docker image for my workshop? If
so, are there any reference materials?

Thanks,

Haibo

**Comment by mdozmorov** [comment]
@haibol2016, check the workshop template, specifically, [here](https://github.com/seandavi/BuildABiocWorkshop2020/blob/8680a38d2e6263cb66ac53a4bc9fd82095028983/vignettes/HOWTO_BUILD_WORKSHOP.Rmd#L46). GitHub actions will build the package web page and the Docker container for you.

**Comment by mdozmorov** [comment]
Everything seems to be in place. @lwaldron, please, close.

**Comment by seaYali** [comment]
Thank you.

Haibo
